---
name: pull-requester
description: |-
  A GitHub Action for running standard checks and automations on pull requests
  for the n3tuk Organisation.

runs:
  using: docker
  image: docker://ghcr.io/n3tuk/pull-requester
  args:
    - run

branding:
  icon: user-check
  color: gray-dark
