---
name: pull-requester
description: |-
  A GitHub Action for running standard checks and automations on pull requests
  for the n3tuk Organisation.

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/scripts/run v1.0.0
      shell: bash

branding:
  icon: user-check
  color: gray-dark
