---
name: pull-requester
description: |-
  A GitHub Action for running standard checks and automations on pull requests
  for the n3tuk Organisation.

inputs:
  title-minimum:
    description: The minimum number of characters that a title should contain
    required: false
    default: '25'
  label-prefixes:
    description: A comma-separated list of label prefixes to check for on a pull request
    required: false
    default: ''
  label-prefix-mode:
    description: Set if any one prefix, or all label prefixes, must match to pass
    required: false
    default: 'false'

runs:
  using: composite
  steps:

    - name: Fetch the pull-requester artifact
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        # Both github.action_repository and .action_ref are not available inside
        # the run: statement, but they are available under env: so set them here
        # so they can be accessed as normal environment variable under the
        # run: statement instead. See the following for more information:
        #   https://github.com/actions/runner/issues/2473
        GH_ACTION_REPOSITORY: ${{ github.action_repository || github.repository }}
        GH_ACTION_REF: ${{ github.action_ref || github.ref_name }}
      run: |-
        ${{ github.action_path }}/scripts/fetch \
          "${GH_ACTION_REPOSITORY}" \
          "${GH_ACTION_REF}"

    - name: Run pull-requester against the pull request
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |-
        ${{ github.action_path }}/bin/pull-requester run \
          --repository=${{ github.repository }} \
          --number=${{ github.event.pull_request.number }} \
          --title-minimum=${{ inputs.title-minimum }} \
          --label-prefixes=${{ inputs.label-prefixes }} \
          --label-prefix-mode=${{ inputs.label-prefix-mode }}

branding:
  icon: user-check
  color: gray-dark
