---
name: pull-requester
description: |-
  A GitHub Action for running standard checks and automations on pull requests
  for the n3tuk Organisation.

runs:
  using: docker
  # Use the same git tag/branch/commit reference given for the action as for the
  # container image to be fetched, although this will only work for anything
  # that has been tagged and released only
  image: ghcr.io/n3tuk/pull-requester:${{ github.action_ref }}
  args:
    - run

branding:
  icon: user-check
  color: gray-dark
