---
name: pull-requester
description: |-
  A GitHub Action for running standard checks and automations on pull requests
  for the n3tuk Organisation.

runs:
  using: composite
  steps:
    - run: |-
        ${{ github.action_path }}/scripts/fetch \
          "${{ github.action_repository }}" \
          "${{ github.action_ref }}"
      shell: bash
    - run: |-
        ${{ github.action_path }}/bin/pull-requester run
      shell: bash

branding:
  icon: user-check
  color: gray-dark
